version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv shell
      - run: python a2/word2vec.py
      - run: python a2/sgd.py
      - run: python a3/parser_transitions.py part_c
      - run: python a3/parser_transitions.py part_d
      - run: python a4/python sanity_check.py 1d
      - run: python a4/python sanity_check.py 1e
      - run: python a4/python sanity_check.py 1f

workflows:
  main:
    jobs:
      - build-and-test
